spring:
  aop:
    proxy-target-class: true
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 13
        max-idle: 10
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 200ms

server:
  port: 8600
  servlet:
    context-path: /martin